[alias]
kernel = [
    "build",
    "-p",
    "arach",
    "--bin",
    "arach",
    "--no-default-features",
    "--features",
    "kernel-bin,reference-driver,fortran-control",
    "--target",
    "x86_64-arach.json",
    "-Z",
    "json-target-spec",
    "-Z",
    "build-std=core,alloc,compiler_builtins",
    "-Z",
    "build-std-features=compiler-builtins-mem",
]
